Cargo.toml, src/main.rs
This will use binary name, version, description etc. from `Cargo.toml` when creating `clap::Command`.
=> Use `Cargo.toml` to generate `clap` command

src/builders/mod.rs, src/builders/skopeo_builder.rs, src/commands/build.rs
Worker node will pass image with `readonly=on`. This requires root fs to be mounted as `ro`. Otherwise there will be kernel panic on boot:
```
[    1.142799] /dev/root: Can't open blockdev
[    1.143454] VFS: Cannot open root device "/dev/sda2" or unknown-block(8,2): error -30
```
Added `--rw-root` flag to `gvltctl build` just in case. This flag probably won't be used ever and may be removed in the future.
=> Builder: change root filesystem default mode to read-only

src/builders/skopeo_builder.rs, src/commands/build.rs
On Fedora the default syslinux MBR binary is under `/usr/share` instead of `/usr/lib` so add it to the search path.
=> Add `/usr/share/syslinux/mbr.bin` to search path

Cargo.toml, src/commands/mod.rs, src/main.rs
Using conditional compilation to make `build` subcommand available only for Linux targets
=> build: subcommand compiled only for Linux targets

LICENSE-APACHE
GitHub license recognition didn't seem to pick up the short form of Apache 2.0 license. This commit uses the original GitHub license template.
=> Adjust Apache license file

.github/workflows/release.yaml
This fixes the release pipeline behavior with respect to leading v's in the tag name. Before checking the version in the cargo.toml this v is removed. Otherwise this enables two more targets for the cross build.
The release will be created in draft mode, so after merging this, we can set the v0.1.0 tag and see the magic happening. :crossed_fingers:
=> prepare CI pipeline for v0.1.0 release

Cargo.toml
`gevulot-rs` had an index out of bounds bug in transaction response message check. This commit updates it to fixed version and bumps up our own version accordingly as well.
=> Bump up a version to v0.1.2 w/ a bugfix

src/builders/mod.rs, src/builders/skopeo_builder.rs, src/commands/build.rs
Instead of creating `/workspace` directory inside VM, we will create `/mnt/input` and `/mnt/output` directories.
We do not create mounts for them in default runtime config (`/usr/lib/mia/config.yaml`). Mounts will be created by EVE through following runtime config. Otherwise it adds more conventions between worker nodes and VMs which makes harder to use custom VMs.
=> build: change `/workspace` to `/input` and `/ouput` dirs

Cargo.lock, Cargo.toml, src/builders/skopeo_builder.rs
New runtime config definition is used.
Also `mia-installer` updated to new version, which doesn't build MIA from sources (instead it downloads pre-built version from GitHub releases). After that issues with `gvltctl` release GitHub workflow should be gone and it should start working properly.
NOTE: `gevulot-rs` revision here is important, because it MUST be aligned with the one used in `mia-installer`. Otherwise build will fail with `mismatched types` error.
Future TODOs:
- Add option for selecting MIA version to `gvltctl build` (it is possible with new `mia-installer`)
=> Switch from `mia_rt_config` to `gevulot_rs::runtime_config`

Cargo.lock, Cargo.toml, src/builders/mod.rs, src/builders/skopeo_builder.rs, src/commands/build.rs
After this changes there will be option `--mia-version`. Examples of usage:
```shell
gvltctl build --mia-version latest ...
gvltctl build --mia-version 0.3.0 ...
gvltctl build --mia-version file:target/x86_64-unknown-linux-gnu/release/mia ...
```
Note that compatibility between `mia-installer` and `mia` is still not guaranteed. The only thing which is checked is that latest `mia-installer` tag can install latest MIA release.
Also: in this PR `mia-installer` version is bumped to allow us to use re-exported `gevulot_rs::runtime_config`.
=> Add option to `gvltctl build` to specify MIA version

src/commands/build.rs
6.12 is latest release and most probably next LTS version so it's good to pin into that one. Using `latest` as default is risky as end users might run into unexpected issues and it's difficult to debug when the used version is "unknown".
=> Default VM kernel to 6.12

.github/workflows/release.yaml
This will help a lot to debug this workflow. Also this will allow releasing tags like `X.Y.Z-pre`.
=> Add manual release trigger

.github/workflows/release.yaml, Cargo.lock, Cargo.toml, README.md
Changes:
- Updated versions of `gevulot-rs` and `mia-installer`
- Added feature `openssl-vendored`
- Refactored release workflow:
- Don't use Cross when building for x86_64 Linux
- Refine releasing targets list
- Specify default shell for the job
- Link release binary statically
After these changes we should be able to automatically release pre-built binaries for:
- `x86_64-unknown-linux-gnu`
- `x86_64-apple-darwin`
- `aarch64-apple-darwin`
whenever a new tag of format `v1.2.3` is pushed.
Also this release workflow can be triggered manually for any ref (tag).
=> 0.1.3 pre-release changes

.containerignore, Cargo.lock, Cargo.toml, Containerfile, build.rs, src/main.rs
`gvltctl --version` will now include:
- commit info (short commit hash or tag and date)
- platform info
- `gevulot-rs` version
Examples:
```
gvltctl 0.1.3-pre (v0.1.3-pre 2024-12-12)
gevulot-rs 0.1.3-pre.3
platform: x86_64-unknown-linux-gnu
```
```
gvltctl 0.1.3-pre (ae0f1431 2024-12-14)
gevulot-rs 0.1.3-pre.3
platform: x86_64-unknown-linux-gnu
```
```
gvltctl 0.1.3-pre (47514d00-dirty)
gevulot-rs 0.1.3-pre.3 (https://github.com/gevulotnetwork/gevulot-rs?rev=f6ba24f22606e76f0fed89c773a8907fa8f72cfd)
platform: x86_64-unknown-linux-gnu
```
```
gvltctl 0.1.3-pre (47514d00-dirty)
gevulot-rs 0.1.3-pre.3 (/home/alea/gevulot/gevulot-rs)
platform: x86_64-unknown-linux-gnu
```
Doesn't work in our current container, because we don't copy `.git/` there.
- This may not work properly, when re-building …
=> Extend version command for gvltctl

src/builders/skopeo_builder.rs
Squashfs is useful for read-only disk images e.g. in case of large auxiliary trusted setup files.
=> Enable SQUASHFS support in the default VM kernel

src/main.rs
`-n` was used for both mnemonic and password options. It was leading to a runtime panic, which appeared only in debug build:
```
thread 'main' panicked at /home/alea/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.20/src/builder/debug_asserts.rs:112:17:
Command get: Short option names must be unique for each argument, but '-n' is in use by both 'mnemonic' and 'password'
```
=> Fix conflicting CLI option short name

Cargo.toml, README.md, src/commands/mod.rs, src/main.rs
This PR removes Linux OS gate from `build` subcommand. So MacOS builds will have this subcommand compiled.
`build` subcommand is now successfully builds (all MIA-related issues are gone).
However building VM is still not supported on MacOS. Instead of gating it and getting different subcommand set on different platforms, we would rather document supported systems in docs.
=> Remove Linux OS gate for build subcommand

Cargo.lock, Cargo.toml, src/builders/mod.rs, src/commands/build.rs, src/commands/mod.rs, src/commands/pins.rs, src/commands/sudo.rs, src/commands/tasks.rs, src/commands/workers.rs, src/commands/workflow.rs, src/main.rs, src/utils.rs, src/version.rs
This PR replaces imperative `clap` Builder approach (with `clap::Command`) with more declarative `clap` Derive approach.
The actual CLI **stays exactly the same** (apart from some fixes in it). Only the internal implementation changed.
Essentially this helps handling CLI args and avoids getting from `clap::ArgMatches` during actual function calls. So we no longer have to report manually errors like `error: ID is required`.
- A lot of code refactored
- Fixed a number of bugs with missing arguments: some commands were expecting arguments, which weren't defined for that `clap::Command` at all - so they were constantly panicing.
- Made `-F/--format` option global, so it is now inherited by any sub-command (however `gvltctl build` doesn't respect this option).
- Improved readability of …
=> Refactor CLI implementation

src/commands/tasks.rs, src/commands/workers.rs, src/main.rs
Doesn't use the new builder from gevulot-rs
=> add delete task subcommand

src/builders_v2/linux_vm/nvidia.rs
Driver names were reported improperly to MIA. Now `install` function returns actual module names, not filenames.
=> Fix bug in NVIDIA drivers installation

src/builders_v2/linux_vm/filesystem/ext4_linux.rs, src/builders_v2/linux_vm/filesystem/fat32.rs, src/builders_v2/linux_vm/filesystem/squashfs.rs, src/builders_v2/linux_vm/image_file.rs, src/builders_v2/linux_vm/kernel.rs, src/builders_v2/linux_vm/mount/mod.rs
Just clear dead code warnings.
This code seems useful in the future, so I don't want to just remove it. Also this may be useful if at some point we would like to expose builder as a library: building VM images with Rust API may be useful for testing e.g.
=> Clear build warnings

Cargo.lock, Cargo.toml, README.md, src/builders_v2/linux_vm/filesystem/squashfs.rs
SquashFS now stores `LazyOpen` instead of `std::fs::File` for each source file. Thus source file will be opened only on `read()` and there will be no file descriptor exhaustion.
There is no performance affect as far as I can tell.
=> Implement LazyReader for SquashFS writing

Cargo.lock, Cargo.toml, build.rs, src/version.rs
When using `gvltctl --version` gevulot-rs version `unknown` was shown too many times. This PR fixes it.
This metadata trickery was also causing `gvltctl` to constantly re-build. This PR also fixes it by upgrading to new version of `shadow-rs`.
=> Fix `gevulot-rs` version printing

src/commands/tasks.rs
Clippy update brought this new lint failure
=> Fix clippy warning about docs identation
